AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  createroom:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.create_room
      Runtime: python3.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::839525500162:role/LabRole'
      Tags:
        name: create_room
      Layers:
        - 'arn:aws:lambda:us-east-1:839525500162:layer:JsonSchemaLayer:4'
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
