AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  getrooms:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.get_rooms
      Runtime: python3.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::839525500162:role/LabRole'
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
