AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  translatetext:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.translate_text
      Runtime: python3.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::839525500162:role/LabRole'
      Layers:
        - 'arn:aws:lambda:us-east-1:839525500162:layer:requestsLayer:2'
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
